export const ERROR_CODES = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NO_PROCESS: "NO_PROCESS",
  INVALID_PROCESS_ACTION: "INVALID_PROCESS_ACTION",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;
