import { ErrorCode } from "../types/api";

export const ERROR_CODES = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  UNAUTHORIZED: "UNAUTHORIZED",
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  PROCESS_NOT_FOUND: "PROCESS_NOT_FOUND",
  INVALID_PROCESS_ACTION: "INVALID_PROCESS_ACTION",
  PROCESS_ALREADY_EXISTS: "PROCESS_ALREADY_EXISTS",
} as const;

export const errorStatusCodes: Record<ErrorCode, number> = {
  INTERNAL_ERROR: 500,
  INVALID_ARGUMENT: 400,
  UNAUTHORIZED: 401,
  CLIENT_NOT_FOUND: 404,
  PROCESS_NOT_FOUND: 404,
  INVALID_PROCESS_ACTION: 409,
  PROCESS_ALREADY_EXISTS: 409,
};
